# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='navigate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(max_length=40)),
                ('nav_href', models.CharField(max_length=40)),
            ],
        ),
    ]
